[Interface]
PrivateKey = 0GPCEcfcuuedvYuUbMiOj1Zepa/c1hS+8b3vQXIpTlU=
Address = 10.66.66.2/24
DNS = 1.1.1.1, 9.9.9.9

[Peer]
PublicKey = TAJXBMNwe9tcpjQhAAD9PMHHi0myTVcuPb4R6kZaN0s=
PresharedKey = 3PYw6G57P3+TOI/ro+7Yv6tGUHw/hI93VzFFmGYNJRY=
Endpoint = 158.101.122.42:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
