[Interface]
PrivateKey = YBtsOSGVCuE9QukKjmulx0l6qi1s/sDrb3InkHe31Fs=
Address = 10.66.66.2/24
DNS = 1.1.1.1, 9.9.9.9

[Peer]
PublicKey = SaUPTgoN+ktR8+aFGLtuKV3poKX7yUdCXxg0q4KeVHw=
PresharedKey = TiitciFTKoS4FMfox3vMOGlkQyO5AAh0YfF3fQ4WQJg=
Endpoint = 150.136.195.244:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
